### ISSUE TITLE
shapeNested -> mir.ndslice.allocation.shape

### ISSUE THREAD

**Issue by 9il** [ShigekiKarita/numir#1]
Hello @ShigekiKarita
`shapeNested` can be replaced with [`mir.ndslice.allocation: shape`](http://docs.algorithm.dlang.io/latest/mir_ndslice_allocation.html#shape)

**Comment by 9il** [comment]
```d
```

**Comment by ShigekiKarita** [comment]
@9il Thanks for your advice! But it doesn't suit me because I want to write like [this `nparray([[1,2],[3,4]])`](https://github.com/ShigekiKarita/numir/blob/13445128b2be751f66f38c00041c3bdaa5d7ac51/source/numir.d#L278-L280) and need it to pass [this test](https://github.com/ShigekiKarita/numir/blob/13445128b2be751f66f38c00041c3bdaa5d7ac51/source/numir.d#L224-L225).
``` d
import std.stdio;
import mir.ndslice.allocation: shape;

auto shapeNested(T)(T[] a)
{
   int err;
   auto ret = shape(a, err);
   if (err)
     throw new Exception("Array has bad shape");
   return ret;
}

unittest
{
    int[2][3] nested = [[1,2],[3,4],[5,6]];
    writeln(nested.shapeNested);
    assert(nested.shapeNested == [3, 2]);
}
```

but this results is [3]. And test fails.

```
$ dub test --compiler=dmd
Generating test runner configuration 'numir-test-library' for 'library' (library).
Performing "unittest" build using dmd for x86_64.
numir 0.0.1+commit.18.g1344512: building configuration "numir-test-library"...
Linking...
Running ./numir-test-library 
[3]
core.exception.AssertError@source/misc.d(17): unittest failure
```
I found the compiler treats the nested [[...]] arg as an array with just first order length. So I have to avoid this behavior by this recursive cast.
```d
size_t[rank!T] shapeNested(T)(T array)
{
    static if (rank!T == 0)
    {
        return [];
    }
    else
    {
        return to!(size_t[rank!T])(array.length ~ shapeNested(array[0]));
    }
}
```
